### ISSUE TITLE
Disable case sensitive search an filter in devextreme datagrid

### ISSUE THREAD

**Issue by lubislutfi** [SergeyMatveev88/drf-dx-datagrid#4]
Hi,
How to DISABLE case sensitive search and filter on drf-dx-datagrid devextreme datagrid?
Regards.

**Comment by SergeyMatveev88** [comment]
Hi, set in settings.py: 
REST_FRAMEWORK = {
   'DRF_DX_DATAGRID': {
       'FILTER_CASE_SENSITIVE': False}
}

**Comment by lubislutfi** [comment]
> Hi, set in settings.py:
> REST_FRAMEWORK = {
> 'DRF_DX_DATAGRID': {
> 'FILTER_CASE_SENSITIVE': False}
> }

Sorry, your code is not working but i've fixed it. Use 'DRF_DX_DATA_GRID' instead of 'DRF_DX_DATAGRID'.
`
REST_FRAMEWORK = {
'DRF_DX_DATA_GRID': {
'FILTER_CASE_SENSITIVE': False}
}
`
Thanks
