### ISSUE TITLE
Default FILTER_CASE_SENSITIVE setting setted to True

### ISSUE THREAD

**Issue by gabmich** [SergeyMatveev88/drf-dx-datagrid#7]
Hi ! First of all, thank you very much for your very useful package. It saved me a lot of work to make my Django Rest Framework => Angular work with Devextreme (sooo powerful lib).

I just wanted to say that I lost some time to figure out why my requests were 'case sensitive only', before finding the reason in the 'filters.py' file. It would perhaps be a good idea to add a line in the doc for the FILTER_CASE_SENSITIVE settings.

BTW, thanks again for your great work ! Best regards.

**Comment by SergeyMatveev88** [comment]
Hi! Fixed. Thank you for the information.
